### PR TITLE
chore(travis): configure secure vars

### PR DESCRIPTION
**Pull request by keithamus**
Hey @lucasfcosta - here are the tokens for this repo.

I'll set up a readme quickly on how to generate these.

### CODE REVIEW

**Comment by lucasfcosta** [comment]
Awesome! 😄 
I'll get everything done ASAP when this gets released.

LGTM!

**Comment by keithamus** [comment]
@meeber @davelosert @vesln does one of you want to `LGTM`?

**Comment by keithamus** [comment]
Oh, nevermind, apparently my LGTM counts 😆

**Comment by lucasfcosta** [comment]
Apparently this PR did not enable the automatic release.
Can any of you restart the build on Travis? I'm trying to and getting success messages, but the builds just won't restart.

**Comment by keithamus** [comment]
@lucasfcosta ahh, it is because your PR was marked as `chore` but should have been `feat` with perhaps `breaking change`. I'll make a quick PR now

**Pull request merged**
