### PR TITLE
feat: grount up rewrite

### PR DESCRIPTION
**Pull request by keithamus**
This commit will trigger a release on the build systems.

### CODE REVIEW

**Comment by keithamus** [comment]
@lucasfcosta want to add a LGTM 😄

**Comment by meeber** [comment]
What is "grount up"? Some kind of hip moose lingo?

LGTM

**Comment by keithamus** [comment]
Ahh, grount is how I spell ground at 1:15am 😸

**Comment by keithamus** [comment]
@meeber fixed the typo - can I get another LGTM for the build gods please.

**Comment by meeber** [comment]
Sorry I only give my LGTM once

**Comment by lucasfcosta** [comment]
Hey guys, great work releasing this! Thanks for the PR @keithamus.

Also, my latest PR rewriting this had ultra-breaking changes and this ended up being release bumping only the `minor` version number, we may have broken lots of people, what do you think about removing the latest `minor` version and republishing this by bumping the `major` version number?

Please share your thoughts on this matter, I'm not sure this would be the correct approach here.

**Comment by keithamus** [comment]
Hmm thats irritating, the `BREAKING CHANGE` wording in the commit should have bumped the major. I think it must have needed a colon, like `BREAKING CHANGE:`. Well, we can bump to a new version and try to deprecate the existing version?

**Comment by lucasfcosta** [comment]
I'm not sure we can [`unpublish`](https://docs.npmjs.com/cli/unpublish) that with NPM's current unpublishment-related policies, but that would be ideal.

If we can't let's just deprecate the version we just released and release a new major.

Also, to do that we need to use `BREAKING CHANGE:` as you've said (at least that's what is written on [their docs](https://github.com/semantic-release/semantic-release#major-breaking-release)).

**Comment by meeber** [comment]
Technically we're not in violation of semantic versioning due to: "Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable."

I don't think we need to mess around with deprecating anything. But I do think we should release 1.0.0 now.

**Comment by lucasfcosta** [comment]
@meeber ah, that's even better then!

Also, I don't think `semantic-release` does that, there's no info about it on their docs so I guess they'll just bump whatever version number matches their rules for commit messages.

**Comment by meeber** [comment]
Okay, I found [the line](https://github.com/conventional-changelog/conventional-changelog/blob/3cae05244e48af9cf4abbef3114060db585a574c/lib/git.js#L70) that detects if a change is breaking, and it does indeed require the colon at the end. I'll submit a new PR to try to get this bumped to 1.0.0.

**Pull request merged**
