### PR TITLE
feat: setPathValue returns the object in which the value was set. Closes #6

### LINKED ISSUE #6: consider returning the target object from set
I migrated from a similar module called lodash-deep. It had the nice feature that the `set` function would return the target object, so you could make a new object from a literal and assign it like this:

`var req = pathval.set({}, 'session.token.modelId', new ObjectID());`

In pathval, `req` ends up undefined here.

### PR DESCRIPTION
**Pull request by lucasfcosta**
This aims to solve #6.
I'm just returning the whole object in which we've set the value.
I also added tests for that.

### CODE REVIEW

**Comment by shvaikalesh** [comment]
LGTM, very clean change. Nice job, @lucasfcosta 👍

**Comment by meeber** [comment]
LGTM

**Comment by meeber** [comment]
Wait it might be good to add a small note about this behavior in the docs so it doesn't go unnoticed and unused.

**Comment by keithamus** [comment]
FYI @shvaikalesh you're not in [the MAINTAINERS file](https://github.com/chaijs/pathval/blob/master/MAINTAINERS), so your LGTM didn't count. Feel free to raise a PR adding your name for this and any other project you'd like to be a part of 😄

**Comment by keithamus** [comment]
(This is also a LGTM from me 😆)

**Pull request merged**
